### ISSUE TITLE
有几个问题

### ISSUE THREAD

**Issue by lyydhy** [544867814/m3u8-MultithreadingDownload#1]
1.useragent那个txt文件不存在
2.好像下载完了候不退出 
3.util.http 这个库安装后还是不行 不过好像不影响使用屏蔽就可以了

**Comment by 544867814** [comment]
util.http 这个是我自定义的不用安装的 
下载完之后会等自动合并后会自动退出需要等几分钟
useragent这个文件啊 我忘了上传了

**Comment by 544867814** [comment]
已经上传了
